name: Scheduled Rebuild
on:
  schedule:
    - cron: "0 */6 * * *" # Every 6 hours
  workflow_dispatch: {} # Manual trigger

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Build
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}