name: Scheduled Rebuild
on:
  schedule:
    - cron: "0 12 */2 * *" # Roughly every 36 hours (noon every other day)
  workflow_dispatch: {} # Manual trigger

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Build
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}